### ISSUE TITLE
Safari 10/11 support by using rgb with alpha values

### ISSUE THREAD

**Issue by TomDeSmet** [crswll/tailwindcss-theme-swapper#18]
This plugin breaks on Safari 10/11 because those browsers don't support alpha channels inside `rgb()`.
I've taken a look at your code and you choose to use `rgb()` but also add the alpha value to it in this notation: `/[alpha]` which older browsers don't understand.

Why not use `rgba()`? That's supported by all browsers.

Those browsers also don't support the notation with spaces you use, they only support comma's in the rgb value.

**Comment by TomDeSmet** [comment]
Any news on this?

**Comment by crswll** [comment]
Hey! Sorry. Started a new job pretty much right after you opened this issue and spaced on it.

Thinking about it again I'm not sure it makes sense since tailwind uses `rgb(r g b / o)` itself and the docs say `In general, Tailwind CSS v3.0 is designed for and tested on the latest stable versions of Chrome, Firefox, Edge, and Safari. It does not support any version of IE, including IE 11` so I think it makes sense to stick to what it supports.
